version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - unused
  settings:
    revive:
      rules:
        - name: exported
  exclusions:
    generated: lax
