// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID         string             `json:"id"`
	CaptureID  string             `json:"capture_id"`
	Kind       string             `json:"kind"`
	MimeType   string             `json:"mime_type"`
	SizeBytes  int64              `json:"size_bytes"`
	ChunkCount int32              `json:"chunk_count"`
	Sha256     pgtype.Text        `json:"sha256"`
	ObjectKey  string             `json:"object_key"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AssetUploadPresign struct {
	ID             string             `json:"id"`
	AssetID        string             `json:"asset_id"`
	ObjectKey      string             `json:"object_key"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	SizeBytes      int64              `json:"size_bytes"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	ActorID     pgtype.Text        `json:"actor_id"`
	Action      string             `json:"action"`
	Subject     string             `json:"subject"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Capture struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	ProjectID             string             `json:"project_id"`
	Source                string             `json:"source"`
	State                 string             `json:"state"`
	Fidelity              string             `json:"fidelity"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	Epoch                 pgtype.Timestamptz `json:"epoch"`
	Env                   []byte             `json:"env"`
	Metadata              []byte             `json:"metadata"`
	Doc                   []byte             `json:"doc"`
	WithheldEventCount    int32              `json:"withheld_event_count"`
	Revision              int64              `json:"revision"`
	ManifestComplete      bool               `json:"manifest_complete"`
	AppliedRulesetVersion pgtype.Int4        `json:"applied_ruleset_version"`
}

type CaptureEvent struct {
	ID        string             `json:"id"`
	CaptureID string             `json:"capture_id"`
	T         int64              `json:"t"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	Redaction []byte             `json:"redaction"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CaptureFieldVersion struct {
	CaptureID  string             `json:"capture_id"`
	Field      string             `json:"field"`
	ServerT    pgtype.Timestamptz `json:"server_t"`
	Revision   int64              `json:"revision"`
	MutationID string             `json:"mutation_id"`
}

type Comment struct {
	ID        string             `json:"id"`
	CaptureID string             `json:"capture_id"`
	AuthorID  string             `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IntegrationBinding struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Provider    string             `json:"provider"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	UserID      string             `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Mutation struct {
	ID          string             `json:"id"`
	CaptureID   string             `json:"capture_id"`
	Op          string             `json:"op"`
	Payload     []byte             `json:"payload"`
	ClientT     int64              `json:"client_t"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	WorkspaceID string             `json:"workspace_id"`
	Seq         pgtype.Int8        `json:"seq"`
}

type Outbox struct {
	ID           string             `json:"id"`
	Topic        string             `json:"topic"`
	Payload      []byte             `json:"payload"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PurgeJob struct {
	ID          string             `json:"id"`
	CaptureID   string             `json:"capture_id"`
	WorkspaceID string             `json:"workspace_id"`
	State       string             `json:"state"`
	ObjectKeys  []byte             `json:"object_keys"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RedactionAuditFinding struct {
	ID                       string             `json:"id"`
	CaptureID                string             `json:"capture_id"`
	WorkspaceID              string             `json:"workspace_id"`
	AppliedRulesetVersion    pgtype.Int4        `json:"applied_ruleset_version"`
	EvaluationRulesetVersion int32              `json:"evaluation_ruleset_version"`
	RuleIds                  []byte             `json:"rule_ids"`
	EventIds                 []byte             `json:"event_ids"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type RedactionRuleset struct {
	Version     int32              `json:"version"`
	WorkspaceID string             `json:"workspace_id"`
	Rules       []byte             `json:"rules"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ShareLink struct {
	ID        string             `json:"id"`
	CaptureID string             `json:"capture_id"`
	Token     string             `json:"token"`
	CreatedBy string             `json:"created_by"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PolicyOverrides []byte             `json:"policy_overrides"`
}
