// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// Step blobs-deleted -> purged's metadata half. The captures row itself
	// cannot be deleted outright: capture_events/comments/mutations reference
	// it by FK and are append-only by trigger (Task 3), so they can never be
	// removed to clear the way for a parent delete — that immutability is
	// deliberate (see 00002_schema.sql), not an oversight this task works
	// around. Instead the disclosable content columns are wiped in place,
	// which is what actually carries redaction/PHI risk; the row itself
	// persists, permanently non-ready, as its own tombstone.
	ClearCaptureContentForPurge(ctx context.Context, id string) (Capture, error)
	// Flips consumed_at exactly once. ON conflict with an already-consumed row
	// the WHERE clause excludes it, so sqlc's :one returns pgx.ErrNoRows —
	// callers read that as "already consumed, refuse" without a second query.
	ConsumeAssetUploadPresign(ctx context.Context, objectKey string) (AssetUploadPresign, error)
	CountAssetsForCapture(ctx context.Context, captureID string) (int64, error)
	CountUnverifiedAssetsForCapture(ctx context.Context, captureID string) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateAssetUploadPresign(ctx context.Context, arg CreateAssetUploadPresignParams) (AssetUploadPresign, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateCapture(ctx context.Context, arg CreateCaptureParams) (Capture, error)
	CreateCaptureEvent(ctx context.Context, arg CreateCaptureEventParams) (CaptureEvent, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateIntegrationBinding(ctx context.Context, arg CreateIntegrationBindingParams) (IntegrationBinding, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	// Plain insert on the client-minted mutation ULID primary key. Replay is
	// idempotent because a duplicate ID hits the PK constraint; callers treat
	// that unique-violation as "already applied" rather than an error. An
	// ON CONFLICT DO UPDATE is deliberately not used here: mutations is
	// append-only (no UPDATE grant for the runtime role), so upserting would
	// defeat the same immutability this table exists to enforce.
	CreateMutation(ctx context.Context, arg CreateMutationParams) (Mutation, error)
	CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (Outbox, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// ON CONFLICT DO NOTHING on the capture_id UNIQUE constraint makes the
	// sweep that creates pending jobs idempotent: running it twice against the
	// same expired capture creates exactly one job. sqlc's :one returns
	// pgx.ErrNoRows when the conflict fires with nothing to return, which
	// callers read as "a job already exists for this capture".
	CreatePurgeJobIfAbsent(ctx context.Context, arg CreatePurgeJobIfAbsentParams) (PurgeJob, error)
	CreateRedactionAuditFinding(ctx context.Context, arg CreateRedactionAuditFindingParams) (RedactionAuditFinding, error)
	CreateRedactionRuleset(ctx context.Context, arg CreateRedactionRulesetParams) (RedactionRuleset, error)
	CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteAssetsForCapture(ctx context.Context, captureID string) (int64, error)
	DeleteProjectForWorkspace(ctx context.Context, arg DeleteProjectForWorkspaceParams) (int64, error)
	DeleteWorkspace(ctx context.Context, id string) error
	GetAsset(ctx context.Context, id string) (Asset, error)
	// Same no-existence-leak shape as LockCaptureForWorkspace: an asset id that
	// belongs to a capture outside the caller's workspace, or doesn't exist at
	// all, is indistinguishable pgx.ErrNoRows to the caller.
	GetAssetForWorkspace(ctx context.Context, arg GetAssetForWorkspaceParams) (Asset, error)
	GetAssetUploadPresignByKey(ctx context.Context, objectKey string) (AssetUploadPresign, error)
	GetAuditLog(ctx context.Context, id string) (AuditLog, error)
	GetCapture(ctx context.Context, id string) (Capture, error)
	GetCaptureEvent(ctx context.Context, id string) (CaptureEvent, error)
	GetCaptureFieldVersion(ctx context.Context, arg GetCaptureFieldVersionParams) (CaptureFieldVersion, error)
	GetCaptureForWorkspace(ctx context.Context, arg GetCaptureForWorkspaceParams) (Capture, error)
	GetComment(ctx context.Context, id string) (Comment, error)
	GetIntegrationBinding(ctx context.Context, id string) (IntegrationBinding, error)
	// The audit's own evaluation ruleset: the newest version on record for the
	// workspace, which may be newer than any given capture's
	// applied_ruleset_version.
	GetLatestRedactionRuleset(ctx context.Context, workspaceID string) (RedactionRuleset, error)
	GetMembership(ctx context.Context, id string) (Membership, error)
	// The RBAC seam: resolves a caller's role in a workspace without
	// distinguishing "no such workspace" from "not a member" — both are zero
	// rows, and callers must turn that into the same not-found response either
	// way (see internal/authz and sync-gateway/internal/authctx.OIDCMiddleware).
	GetMembershipByWorkspaceAndUser(ctx context.Context, arg GetMembershipByWorkspaceAndUserParams) (Membership, error)
	GetMutation(ctx context.Context, id string) (Mutation, error)
	GetOutboxEntry(ctx context.Context, id string) (Outbox, error)
	GetProject(ctx context.Context, id string) (Project, error)
	// Scoped by workspace_id so a project ID belonging to another workspace
	// returns pgx.ErrNoRows rather than another workspace's data — the
	// non-disclosing cross-workspace read.
	GetProjectForWorkspace(ctx context.Context, arg GetProjectForWorkspaceParams) (Project, error)
	GetPurgeJob(ctx context.Context, id string) (PurgeJob, error)
	GetPurgeJobByCapture(ctx context.Context, captureID string) (PurgeJob, error)
	GetRedactionRuleset(ctx context.Context, version int32) (RedactionRuleset, error)
	GetShareLink(ctx context.Context, id string) (ShareLink, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	// Same no-existence-leak shape as GetProjectForWorkspace/GetAssetForWorkspace:
	// a workspace id the caller isn't a member of returns pgx.ErrNoRows
	// identically to a workspace id that doesn't exist at all.
	GetWorkspaceForMember(ctx context.Context, arg GetWorkspaceForMemberParams) (Workspace, error)
	// Idempotent variant of CreateMutation used by sync-gateway: ON CONFLICT DO
	// NOTHING never updates the row (mutations stays append-only, same
	// reasoning as CreateMutation above), it just makes a duplicate insert a
	// no-op instead of a unique-violation error. sqlc's :one returns
	// pgx.ErrNoRows when the conflict fires with nothing to return, which
	// callers read as "already applied, do not reprocess". workspace_id is
	// stamped here (Task 6) so PullDeltas can filter the delta log without a
	// join back to captures.
	InsertMutationIfNew(ctx context.Context, arg InsertMutationIfNewParams) (Mutation, error)
	// The orphan detector's "live" half: every object key any surviving asset
	// row still points at.
	ListAllAssetObjectKeys(ctx context.Context) ([]string, error)
	ListAssetObjectKeysByCapture(ctx context.Context, captureID string) ([]string, error)
	ListCaptureEventsByCapture(ctx context.Context, captureID string) ([]CaptureEvent, error)
	ListCapturesByWorkspace(ctx context.Context, workspaceID string) ([]Capture, error)
	// Task 13: the purge state machine's persistence. A purge_jobs row is
	// created once a ready capture passes its retention window and advances
	// through pending -> tombstoned -> blobs-deleting -> blobs-deleted ->
	// purged; see services/purge-job/internal/purge.
	// Every ready capture in workspace_id created at or before threshold —
	// threshold is computed in Go from the workspace's resolved policy
	// (policy.Resolve(...).RetentionDays), since retention resolution is a
	// pure Go function, not something to duplicate in SQL.
	ListCapturesPastRetention(ctx context.Context, arg ListCapturesPastRetentionParams) ([]Capture, error)
	// Task 6's delta log: every mutation applied in workspace_id with seq >
	// since, ordered by seq so a client resumes exactly where it left off
	// regardless of which capture each mutation touched. limit is passed as
	// requested-page-size+1 by the caller so it can detect has_more without a
	// second COUNT query.
	ListMutationsSinceRevision(ctx context.Context, arg ListMutationsSinceRevisionParams) ([]Mutation, error)
	ListProjectsByWorkspace(ctx context.Context, workspaceID string) ([]Project, error)
	// Every object key any purge job (at any state, including purged — job
	// rows are retained briefly as completion evidence) has ever recorded as
	// belonging to a capture being purged. Part of the orphan detector's
	// "referenced" set alongside ListAllAssetObjectKeys.
	ListPurgeJobObjectKeys(ctx context.Context) ([][]byte, error)
	// The reconciliation sweep's resume list: every job stuck short of the
	// terminal state, regardless of how long ago it last advanced.
	ListPurgeJobsNotPurged(ctx context.Context) ([]PurgeJob, error)
	// redaction-audit's poll source: only "ready" captures have crossed the
	// gate (invariant 1) and are worth re-checking; nothing earlier in the
	// pipeline has finished redacting yet.
	ListReadyCapturesByWorkspace(ctx context.Context, workspaceID string) ([]Capture, error)
	ListRedactionAuditFindingsByCapture(ctx context.Context, captureID string) ([]RedactionAuditFinding, error)
	// redaction-audit polls every workspace; unlike ListWorkspacesForUser this
	// is not scoped to a caller, since the audit acts as the platform, not on
	// behalf of a member.
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	ListWorkspacesForUser(ctx context.Context, userID string) ([]Workspace, error)
	// Workspace and existence are checked in one predicate so a mutation
	// naming a capture outside the caller's workspace fails the same way as a
	// mutation naming a capture that doesn't exist at all — the caller cannot
	// tell the two cases apart, which is the point (no existence leak across
	// workspaces). FOR UPDATE serializes concurrent revision increments on the
	// same capture.
	LockCaptureForWorkspace(ctx context.Context, arg LockCaptureForWorkspaceParams) (Capture, error)
	MarkAssetVerified(ctx context.Context, arg MarkAssetVerifiedParams) (Asset, error)
	RevokeShareLink(ctx context.Context, id string) (ShareLink, error)
	SetCaptureManifestComplete(ctx context.Context, arg SetCaptureManifestCompleteParams) (Capture, error)
	// Step tombstoned -> blobs-deleting: records exactly which object keys must
	// be deleted before flipping state, so a resume at blobs-deleting reads
	// the keys back from here rather than re-deriving them from assets (which
	// may already be gone by the time of a resume attempted after purged).
	SetPurgeJobObjectKeysAndState(ctx context.Context, arg SetPurgeJobObjectKeysAndStateParams) (PurgeJob, error)
	SetPurgeJobState(ctx context.Context, arg SetPurgeJobStateParams) (PurgeJob, error)
	// Step pending -> tombstoned's capture-side half: flips state to 'expired'
	// (spec: "retention window elapsed; assets purged"), which immediately
	// makes gateCapture/gateCaptureEvents/the share resolver treat it as
	// non-disclosable — invariant 1's "the gate is state === 'ready'" already
	// covers 'expired' for free, so tombstoning needs no separate check
	// anywhere else.
	TombstoneCaptureForPurge(ctx context.Context, id string) (Capture, error)
	UpdateCaptureRevisionAndDoc(ctx context.Context, arg UpdateCaptureRevisionAndDocParams) (Capture, error)
	UpdateProjectForWorkspace(ctx context.Context, arg UpdateProjectForWorkspaceParams) (Project, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpdateWorkspacePolicyOverrides(ctx context.Context, arg UpdateWorkspacePolicyOverridesParams) (Workspace, error)
	// Creates the manifest entry (ADR-012: "the manifest entry for each asset
	// carries the expected size and content hash before the PUT is issued") on
	// first request, or repoints object_key at a freshly minted key on
	// re-request. sha256/size_bytes/verified_at are deliberately left untouched
	// here — they only ever change via MarkAssetVerified, so a re-request can
	// never itself flip a verified asset back to unverified.
	UpsertAssetForUpload(ctx context.Context, arg UpsertAssetForUploadParams) (Asset, error)
	UpsertCaptureFieldVersion(ctx context.Context, arg UpsertCaptureFieldVersionParams) (CaptureFieldVersion, error)
	// Identity is minted by the IdP (the OIDC subject), not by us, so first
	// login upserts a local user row keyed on that subject rather than
	// inserting and failing on conflict.
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
