// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateCapture(ctx context.Context, arg CreateCaptureParams) (Capture, error)
	CreateCaptureEvent(ctx context.Context, arg CreateCaptureEventParams) (CaptureEvent, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateIntegrationBinding(ctx context.Context, arg CreateIntegrationBindingParams) (IntegrationBinding, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	// Plain insert on the client-minted mutation ULID primary key. Replay is
	// idempotent because a duplicate ID hits the PK constraint; callers treat
	// that unique-violation as "already applied" rather than an error. An
	// ON CONFLICT DO UPDATE is deliberately not used here: mutations is
	// append-only (no UPDATE grant for the runtime role), so upserting would
	// defeat the same immutability this table exists to enforce.
	CreateMutation(ctx context.Context, arg CreateMutationParams) (Mutation, error)
	CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (Outbox, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRedactionRuleset(ctx context.Context, arg CreateRedactionRulesetParams) (RedactionRuleset, error)
	CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	GetAsset(ctx context.Context, id string) (Asset, error)
	GetAuditLog(ctx context.Context, id string) (AuditLog, error)
	GetCapture(ctx context.Context, id string) (Capture, error)
	GetCaptureEvent(ctx context.Context, id string) (CaptureEvent, error)
	GetCaptureFieldVersion(ctx context.Context, arg GetCaptureFieldVersionParams) (CaptureFieldVersion, error)
	GetComment(ctx context.Context, id string) (Comment, error)
	GetIntegrationBinding(ctx context.Context, id string) (IntegrationBinding, error)
	GetMembership(ctx context.Context, id string) (Membership, error)
	GetMutation(ctx context.Context, id string) (Mutation, error)
	GetOutboxEntry(ctx context.Context, id string) (Outbox, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetRedactionRuleset(ctx context.Context, version int32) (RedactionRuleset, error)
	GetShareLink(ctx context.Context, id string) (ShareLink, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	// Idempotent variant of CreateMutation used by sync-gateway: ON CONFLICT DO
	// NOTHING never updates the row (mutations stays append-only, same
	// reasoning as CreateMutation above), it just makes a duplicate insert a
	// no-op instead of a unique-violation error. sqlc's :one returns
	// pgx.ErrNoRows when the conflict fires with nothing to return, which
	// callers read as "already applied, do not reprocess".
	InsertMutationIfNew(ctx context.Context, arg InsertMutationIfNewParams) (Mutation, error)
	ListCaptureEventsByCapture(ctx context.Context, captureID string) ([]CaptureEvent, error)
	// Workspace and existence are checked in one predicate so a mutation
	// naming a capture outside the caller's workspace fails the same way as a
	// mutation naming a capture that doesn't exist at all — the caller cannot
	// tell the two cases apart, which is the point (no existence leak across
	// workspaces). FOR UPDATE serializes concurrent revision increments on the
	// same capture.
	LockCaptureForWorkspace(ctx context.Context, arg LockCaptureForWorkspaceParams) (Capture, error)
	RevokeShareLink(ctx context.Context, id string) (ShareLink, error)
	UpdateCaptureRevisionAndDoc(ctx context.Context, arg UpdateCaptureRevisionAndDocParams) (Capture, error)
	UpsertCaptureFieldVersion(ctx context.Context, arg UpsertCaptureFieldVersionParams) (CaptureFieldVersion, error)
}

var _ Querier = (*Queries)(nil)
