// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAssetUploadPresign = `-- name: ConsumeAssetUploadPresign :one
UPDATE asset_upload_presigns SET consumed_at = now()
WHERE object_key = $1 AND consumed_at IS NULL
RETURNING id, asset_id, object_key, checksum_sha256, size_bytes, expires_at, consumed_at, created_at
`

// Flips consumed_at exactly once. ON conflict with an already-consumed row
// the WHERE clause excludes it, so sqlc's :one returns pgx.ErrNoRows —
// callers read that as "already consumed, refuse" without a second query.
func (q *Queries) ConsumeAssetUploadPresign(ctx context.Context, objectKey string) (AssetUploadPresign, error) {
	row := q.db.QueryRow(ctx, consumeAssetUploadPresign, objectKey)
	var i AssetUploadPresign
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countAssetsForCapture = `-- name: CountAssetsForCapture :one
SELECT count(*) FROM assets WHERE capture_id = $1
`

func (q *Queries) CountAssetsForCapture(ctx context.Context, captureID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetsForCapture, captureID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnverifiedAssetsForCapture = `-- name: CountUnverifiedAssetsForCapture :one
SELECT count(*) FROM assets WHERE capture_id = $1 AND verified_at IS NULL
`

func (q *Queries) CountUnverifiedAssetsForCapture(ctx context.Context, captureID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnverifiedAssetsForCapture, captureID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (id, capture_id, kind, mime_type, size_bytes, chunk_count, sha256, object_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, capture_id, kind, mime_type, size_bytes, chunk_count, sha256, object_key, verified_at, created_at
`

type CreateAssetParams struct {
	ID         string      `json:"id"`
	CaptureID  string      `json:"capture_id"`
	Kind       string      `json:"kind"`
	MimeType   string      `json:"mime_type"`
	SizeBytes  int64       `json:"size_bytes"`
	ChunkCount int32       `json:"chunk_count"`
	Sha256     pgtype.Text `json:"sha256"`
	ObjectKey  string      `json:"object_key"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.CaptureID,
		arg.Kind,
		arg.MimeType,
		arg.SizeBytes,
		arg.ChunkCount,
		arg.Sha256,
		arg.ObjectKey,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Kind,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.Sha256,
		&i.ObjectKey,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAssetUploadPresign = `-- name: CreateAssetUploadPresign :one
INSERT INTO asset_upload_presigns (id, asset_id, object_key, checksum_sha256, size_bytes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, asset_id, object_key, checksum_sha256, size_bytes, expires_at, consumed_at, created_at
`

type CreateAssetUploadPresignParams struct {
	ID             string             `json:"id"`
	AssetID        string             `json:"asset_id"`
	ObjectKey      string             `json:"object_key"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	SizeBytes      int64              `json:"size_bytes"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAssetUploadPresign(ctx context.Context, arg CreateAssetUploadPresignParams) (AssetUploadPresign, error) {
	row := q.db.QueryRow(ctx, createAssetUploadPresign,
		arg.ID,
		arg.AssetID,
		arg.ObjectKey,
		arg.ChecksumSha256,
		arg.SizeBytes,
		arg.ExpiresAt,
	)
	var i AssetUploadPresign
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (id, workspace_id, actor_id, action, subject, details)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, workspace_id, actor_id, action, subject, details, created_at
`

type CreateAuditLogParams struct {
	ID          string      `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	ActorID     pgtype.Text `json:"actor_id"`
	Action      string      `json:"action"`
	Subject     string      `json:"subject"`
	Details     []byte      `json:"details"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Action,
		arg.Subject,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.Action,
		&i.Subject,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const createCapture = `-- name: CreateCapture :one
INSERT INTO captures (
    id, workspace_id, project_id, source, state, fidelity, epoch, env,
    metadata, doc, withheld_event_count, revision, manifest_complete,
    applied_ruleset_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, workspace_id, project_id, source, state, fidelity, created_at, epoch, env, metadata, doc, withheld_event_count, revision, manifest_complete, applied_ruleset_version
`

type CreateCaptureParams struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	ProjectID             string             `json:"project_id"`
	Source                string             `json:"source"`
	State                 string             `json:"state"`
	Fidelity              string             `json:"fidelity"`
	Epoch                 pgtype.Timestamptz `json:"epoch"`
	Env                   []byte             `json:"env"`
	Metadata              []byte             `json:"metadata"`
	Doc                   []byte             `json:"doc"`
	WithheldEventCount    int32              `json:"withheld_event_count"`
	Revision              int64              `json:"revision"`
	ManifestComplete      bool               `json:"manifest_complete"`
	AppliedRulesetVersion pgtype.Int4        `json:"applied_ruleset_version"`
}

func (q *Queries) CreateCapture(ctx context.Context, arg CreateCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, createCapture,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Source,
		arg.State,
		arg.Fidelity,
		arg.Epoch,
		arg.Env,
		arg.Metadata,
		arg.Doc,
		arg.WithheldEventCount,
		arg.Revision,
		arg.ManifestComplete,
		arg.AppliedRulesetVersion,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Source,
		&i.State,
		&i.Fidelity,
		&i.CreatedAt,
		&i.Epoch,
		&i.Env,
		&i.Metadata,
		&i.Doc,
		&i.WithheldEventCount,
		&i.Revision,
		&i.ManifestComplete,
		&i.AppliedRulesetVersion,
	)
	return i, err
}

const createCaptureEvent = `-- name: CreateCaptureEvent :one
INSERT INTO capture_events (id, capture_id, t, kind, payload, redaction)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, capture_id, t, kind, payload, redaction, created_at
`

type CreateCaptureEventParams struct {
	ID        string `json:"id"`
	CaptureID string `json:"capture_id"`
	T         int64  `json:"t"`
	Kind      string `json:"kind"`
	Payload   []byte `json:"payload"`
	Redaction []byte `json:"redaction"`
}

func (q *Queries) CreateCaptureEvent(ctx context.Context, arg CreateCaptureEventParams) (CaptureEvent, error) {
	row := q.db.QueryRow(ctx, createCaptureEvent,
		arg.ID,
		arg.CaptureID,
		arg.T,
		arg.Kind,
		arg.Payload,
		arg.Redaction,
	)
	var i CaptureEvent
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.T,
		&i.Kind,
		&i.Payload,
		&i.Redaction,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, capture_id, author_id, body) VALUES ($1, $2, $3, $4) RETURNING id, capture_id, author_id, body, created_at
`

type CreateCommentParams struct {
	ID        string `json:"id"`
	CaptureID string `json:"capture_id"`
	AuthorID  string `json:"author_id"`
	Body      string `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.CaptureID,
		arg.AuthorID,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createIntegrationBinding = `-- name: CreateIntegrationBinding :one
INSERT INTO integration_bindings (id, workspace_id, provider, config)
VALUES ($1, $2, $3, $4) RETURNING id, workspace_id, provider, config, created_at
`

type CreateIntegrationBindingParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Provider    string `json:"provider"`
	Config      []byte `json:"config"`
}

func (q *Queries) CreateIntegrationBinding(ctx context.Context, arg CreateIntegrationBindingParams) (IntegrationBinding, error) {
	row := q.db.QueryRow(ctx, createIntegrationBinding,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.Config,
	)
	var i IntegrationBinding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (id, workspace_id, user_id, role) VALUES ($1, $2, $3, $4) RETURNING id, workspace_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createMutation = `-- name: CreateMutation :one
INSERT INTO mutations (id, capture_id, op, payload, client_t)
VALUES ($1, $2, $3, $4, $5) RETURNING id, capture_id, op, payload, client_t, created_at, workspace_id, seq
`

type CreateMutationParams struct {
	ID        string `json:"id"`
	CaptureID string `json:"capture_id"`
	Op        string `json:"op"`
	Payload   []byte `json:"payload"`
	ClientT   int64  `json:"client_t"`
}

// Plain insert on the client-minted mutation ULID primary key. Replay is
// idempotent because a duplicate ID hits the PK constraint; callers treat
// that unique-violation as "already applied" rather than an error. An
// ON CONFLICT DO UPDATE is deliberately not used here: mutations is
// append-only (no UPDATE grant for the runtime role), so upserting would
// defeat the same immutability this table exists to enforce.
func (q *Queries) CreateMutation(ctx context.Context, arg CreateMutationParams) (Mutation, error) {
	row := q.db.QueryRow(ctx, createMutation,
		arg.ID,
		arg.CaptureID,
		arg.Op,
		arg.Payload,
		arg.ClientT,
	)
	var i Mutation
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Op,
		&i.Payload,
		&i.ClientT,
		&i.CreatedAt,
		&i.WorkspaceID,
		&i.Seq,
	)
	return i, err
}

const createOutboxEntry = `-- name: CreateOutboxEntry :one
INSERT INTO outbox (id, topic, payload) VALUES ($1, $2, $3) RETURNING id, topic, payload, dispatched_at, created_at
`

type CreateOutboxEntryParams struct {
	ID      string `json:"id"`
	Topic   string `json:"topic"`
	Payload []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEntry, arg.ID, arg.Topic, arg.Payload)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.DispatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, workspace_id, name) VALUES ($1, $2, $3) RETURNING id, workspace_id, name, created_at
`

type CreateProjectParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.WorkspaceID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createRedactionRuleset = `-- name: CreateRedactionRuleset :one
INSERT INTO redaction_rulesets (version, workspace_id, rules) VALUES ($1, $2, $3) RETURNING version, workspace_id, rules, created_at
`

type CreateRedactionRulesetParams struct {
	Version     int32  `json:"version"`
	WorkspaceID string `json:"workspace_id"`
	Rules       []byte `json:"rules"`
}

func (q *Queries) CreateRedactionRuleset(ctx context.Context, arg CreateRedactionRulesetParams) (RedactionRuleset, error) {
	row := q.db.QueryRow(ctx, createRedactionRuleset, arg.Version, arg.WorkspaceID, arg.Rules)
	var i RedactionRuleset
	err := row.Scan(
		&i.Version,
		&i.WorkspaceID,
		&i.Rules,
		&i.CreatedAt,
	)
	return i, err
}

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (id, capture_id, token, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, capture_id, token, created_by, revoked_at, expires_at, created_at
`

type CreateShareLinkParams struct {
	ID        string             `json:"id"`
	CaptureID string             `json:"capture_id"`
	Token     string             `json:"token"`
	CreatedBy string             `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.ID,
		arg.CaptureID,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Token,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name) VALUES ($1, $2, $3) RETURNING id, email, name, created_at
`

type CreateUserParams struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name) VALUES ($1, $2) RETURNING id, name, created_at, policy_overrides
`

type CreateWorkspaceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.PolicyOverrides,
	)
	return i, err
}

const deleteProjectForWorkspace = `-- name: DeleteProjectForWorkspace :execrows
DELETE FROM projects WHERE id = $1 AND workspace_id = $2
`

type DeleteProjectForWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteProjectForWorkspace(ctx context.Context, arg DeleteProjectForWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectForWorkspace, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, capture_id, kind, mime_type, size_bytes, chunk_count, sha256, object_key, verified_at, created_at FROM assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Kind,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.Sha256,
		&i.ObjectKey,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetForWorkspace = `-- name: GetAssetForWorkspace :one
SELECT a.id, a.capture_id, a.kind, a.mime_type, a.size_bytes, a.chunk_count, a.sha256, a.object_key, a.verified_at, a.created_at FROM assets a
JOIN captures c ON c.id = a.capture_id
WHERE a.id = $1 AND a.capture_id = $2 AND c.workspace_id = $3
`

type GetAssetForWorkspaceParams struct {
	ID          string `json:"id"`
	CaptureID   string `json:"capture_id"`
	WorkspaceID string `json:"workspace_id"`
}

// Same no-existence-leak shape as LockCaptureForWorkspace: an asset id that
// belongs to a capture outside the caller's workspace, or doesn't exist at
// all, is indistinguishable pgx.ErrNoRows to the caller.
func (q *Queries) GetAssetForWorkspace(ctx context.Context, arg GetAssetForWorkspaceParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetForWorkspace, arg.ID, arg.CaptureID, arg.WorkspaceID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Kind,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.Sha256,
		&i.ObjectKey,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetUploadPresignByKey = `-- name: GetAssetUploadPresignByKey :one
SELECT id, asset_id, object_key, checksum_sha256, size_bytes, expires_at, consumed_at, created_at FROM asset_upload_presigns WHERE object_key = $1
`

func (q *Queries) GetAssetUploadPresignByKey(ctx context.Context, objectKey string) (AssetUploadPresign, error) {
	row := q.db.QueryRow(ctx, getAssetUploadPresignByKey, objectKey)
	var i AssetUploadPresign
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, workspace_id, actor_id, action, subject, details, created_at FROM audit_log WHERE id = $1
`

func (q *Queries) GetAuditLog(ctx context.Context, id string) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.Action,
		&i.Subject,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getCapture = `-- name: GetCapture :one
SELECT id, workspace_id, project_id, source, state, fidelity, created_at, epoch, env, metadata, doc, withheld_event_count, revision, manifest_complete, applied_ruleset_version FROM captures WHERE id = $1
`

func (q *Queries) GetCapture(ctx context.Context, id string) (Capture, error) {
	row := q.db.QueryRow(ctx, getCapture, id)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Source,
		&i.State,
		&i.Fidelity,
		&i.CreatedAt,
		&i.Epoch,
		&i.Env,
		&i.Metadata,
		&i.Doc,
		&i.WithheldEventCount,
		&i.Revision,
		&i.ManifestComplete,
		&i.AppliedRulesetVersion,
	)
	return i, err
}

const getCaptureEvent = `-- name: GetCaptureEvent :one
SELECT id, capture_id, t, kind, payload, redaction, created_at FROM capture_events WHERE id = $1
`

func (q *Queries) GetCaptureEvent(ctx context.Context, id string) (CaptureEvent, error) {
	row := q.db.QueryRow(ctx, getCaptureEvent, id)
	var i CaptureEvent
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.T,
		&i.Kind,
		&i.Payload,
		&i.Redaction,
		&i.CreatedAt,
	)
	return i, err
}

const getCaptureFieldVersion = `-- name: GetCaptureFieldVersion :one
SELECT capture_id, field, server_t, revision, mutation_id FROM capture_field_versions WHERE capture_id = $1 AND field = $2
`

type GetCaptureFieldVersionParams struct {
	CaptureID string `json:"capture_id"`
	Field     string `json:"field"`
}

func (q *Queries) GetCaptureFieldVersion(ctx context.Context, arg GetCaptureFieldVersionParams) (CaptureFieldVersion, error) {
	row := q.db.QueryRow(ctx, getCaptureFieldVersion, arg.CaptureID, arg.Field)
	var i CaptureFieldVersion
	err := row.Scan(
		&i.CaptureID,
		&i.Field,
		&i.ServerT,
		&i.Revision,
		&i.MutationID,
	)
	return i, err
}

const getCaptureForWorkspace = `-- name: GetCaptureForWorkspace :one
SELECT id, workspace_id, project_id, source, state, fidelity, created_at, epoch, env, metadata, doc, withheld_event_count, revision, manifest_complete, applied_ruleset_version FROM captures WHERE id = $1 AND workspace_id = $2
`

type GetCaptureForWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetCaptureForWorkspace(ctx context.Context, arg GetCaptureForWorkspaceParams) (Capture, error) {
	row := q.db.QueryRow(ctx, getCaptureForWorkspace, arg.ID, arg.WorkspaceID)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Source,
		&i.State,
		&i.Fidelity,
		&i.CreatedAt,
		&i.Epoch,
		&i.Env,
		&i.Metadata,
		&i.Doc,
		&i.WithheldEventCount,
		&i.Revision,
		&i.ManifestComplete,
		&i.AppliedRulesetVersion,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, capture_id, author_id, body, created_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getIntegrationBinding = `-- name: GetIntegrationBinding :one
SELECT id, workspace_id, provider, config, created_at FROM integration_bindings WHERE id = $1
`

func (q *Queries) GetIntegrationBinding(ctx context.Context, id string) (IntegrationBinding, error) {
	row := q.db.QueryRow(ctx, getIntegrationBinding, id)
	var i IntegrationBinding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, workspace_id, user_id, role, created_at FROM memberships WHERE id = $1
`

func (q *Queries) GetMembership(ctx context.Context, id string) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByWorkspaceAndUser = `-- name: GetMembershipByWorkspaceAndUser :one
SELECT id, workspace_id, user_id, role, created_at FROM memberships WHERE workspace_id = $1 AND user_id = $2
`

type GetMembershipByWorkspaceAndUserParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

// The RBAC seam: resolves a caller's role in a workspace without
// distinguishing "no such workspace" from "not a member" — both are zero
// rows, and callers must turn that into the same not-found response either
// way (see internal/authz and sync-gateway/internal/authctx.OIDCMiddleware).
func (q *Queries) GetMembershipByWorkspaceAndUser(ctx context.Context, arg GetMembershipByWorkspaceAndUserParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByWorkspaceAndUser, arg.WorkspaceID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getMutation = `-- name: GetMutation :one
SELECT id, capture_id, op, payload, client_t, created_at, workspace_id, seq FROM mutations WHERE id = $1
`

func (q *Queries) GetMutation(ctx context.Context, id string) (Mutation, error) {
	row := q.db.QueryRow(ctx, getMutation, id)
	var i Mutation
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Op,
		&i.Payload,
		&i.ClientT,
		&i.CreatedAt,
		&i.WorkspaceID,
		&i.Seq,
	)
	return i, err
}

const getOutboxEntry = `-- name: GetOutboxEntry :one
SELECT id, topic, payload, dispatched_at, created_at FROM outbox WHERE id = $1
`

func (q *Queries) GetOutboxEntry(ctx context.Context, id string) (Outbox, error) {
	row := q.db.QueryRow(ctx, getOutboxEntry, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.DispatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, name, created_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectForWorkspace = `-- name: GetProjectForWorkspace :one
SELECT id, workspace_id, name, created_at FROM projects WHERE id = $1 AND workspace_id = $2
`

type GetProjectForWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

// Scoped by workspace_id so a project ID belonging to another workspace
// returns pgx.ErrNoRows rather than another workspace's data — the
// non-disclosing cross-workspace read.
func (q *Queries) GetProjectForWorkspace(ctx context.Context, arg GetProjectForWorkspaceParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForWorkspace, arg.ID, arg.WorkspaceID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getRedactionRuleset = `-- name: GetRedactionRuleset :one
SELECT version, workspace_id, rules, created_at FROM redaction_rulesets WHERE version = $1
`

func (q *Queries) GetRedactionRuleset(ctx context.Context, version int32) (RedactionRuleset, error) {
	row := q.db.QueryRow(ctx, getRedactionRuleset, version)
	var i RedactionRuleset
	err := row.Scan(
		&i.Version,
		&i.WorkspaceID,
		&i.Rules,
		&i.CreatedAt,
	)
	return i, err
}

const getShareLink = `-- name: GetShareLink :one
SELECT id, capture_id, token, created_by, revoked_at, expires_at, created_at FROM share_links WHERE id = $1
`

func (q *Queries) GetShareLink(ctx context.Context, id string) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLink, id)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Token,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at, policy_overrides FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.PolicyOverrides,
	)
	return i, err
}

const getWorkspaceForMember = `-- name: GetWorkspaceForMember :one
SELECT w.id, w.name, w.created_at, w.policy_overrides FROM workspaces w
JOIN memberships m ON m.workspace_id = w.id
WHERE w.id = $1 AND m.user_id = $2
`

type GetWorkspaceForMemberParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// Same no-existence-leak shape as GetProjectForWorkspace/GetAssetForWorkspace:
// a workspace id the caller isn't a member of returns pgx.ErrNoRows
// identically to a workspace id that doesn't exist at all.
func (q *Queries) GetWorkspaceForMember(ctx context.Context, arg GetWorkspaceForMemberParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForMember, arg.ID, arg.UserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.PolicyOverrides,
	)
	return i, err
}

const insertMutationIfNew = `-- name: InsertMutationIfNew :one
INSERT INTO mutations (id, capture_id, workspace_id, op, payload, client_t)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO NOTHING
RETURNING id, capture_id, op, payload, client_t, created_at, workspace_id, seq
`

type InsertMutationIfNewParams struct {
	ID          string `json:"id"`
	CaptureID   string `json:"capture_id"`
	WorkspaceID string `json:"workspace_id"`
	Op          string `json:"op"`
	Payload     []byte `json:"payload"`
	ClientT     int64  `json:"client_t"`
}

// Idempotent variant of CreateMutation used by sync-gateway: ON CONFLICT DO
// NOTHING never updates the row (mutations stays append-only, same
// reasoning as CreateMutation above), it just makes a duplicate insert a
// no-op instead of a unique-violation error. sqlc's :one returns
// pgx.ErrNoRows when the conflict fires with nothing to return, which
// callers read as "already applied, do not reprocess". workspace_id is
// stamped here (Task 6) so PullDeltas can filter the delta log without a
// join back to captures.
func (q *Queries) InsertMutationIfNew(ctx context.Context, arg InsertMutationIfNewParams) (Mutation, error) {
	row := q.db.QueryRow(ctx, insertMutationIfNew,
		arg.ID,
		arg.CaptureID,
		arg.WorkspaceID,
		arg.Op,
		arg.Payload,
		arg.ClientT,
	)
	var i Mutation
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Op,
		&i.Payload,
		&i.ClientT,
		&i.CreatedAt,
		&i.WorkspaceID,
		&i.Seq,
	)
	return i, err
}

const listCaptureEventsByCapture = `-- name: ListCaptureEventsByCapture :many
SELECT id, capture_id, t, kind, payload, redaction, created_at FROM capture_events WHERE capture_id = $1 ORDER BY t ASC
`

func (q *Queries) ListCaptureEventsByCapture(ctx context.Context, captureID string) ([]CaptureEvent, error) {
	rows, err := q.db.Query(ctx, listCaptureEventsByCapture, captureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureEvent
	for rows.Next() {
		var i CaptureEvent
		if err := rows.Scan(
			&i.ID,
			&i.CaptureID,
			&i.T,
			&i.Kind,
			&i.Payload,
			&i.Redaction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapturesByWorkspace = `-- name: ListCapturesByWorkspace :many
SELECT id, workspace_id, project_id, source, state, fidelity, created_at, epoch, env, metadata, doc, withheld_event_count, revision, manifest_complete, applied_ruleset_version FROM captures WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListCapturesByWorkspace(ctx context.Context, workspaceID string) ([]Capture, error) {
	rows, err := q.db.Query(ctx, listCapturesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Source,
			&i.State,
			&i.Fidelity,
			&i.CreatedAt,
			&i.Epoch,
			&i.Env,
			&i.Metadata,
			&i.Doc,
			&i.WithheldEventCount,
			&i.Revision,
			&i.ManifestComplete,
			&i.AppliedRulesetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutationsSinceRevision = `-- name: ListMutationsSinceRevision :many
SELECT id, capture_id, op, payload, client_t, created_at, workspace_id, seq FROM mutations
WHERE workspace_id = $1 AND seq > $2
ORDER BY seq ASC
LIMIT $3
`

type ListMutationsSinceRevisionParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Seq         pgtype.Int8 `json:"seq"`
	Limit       int32       `json:"limit"`
}

// Task 6's delta log: every mutation applied in workspace_id with seq >
// since, ordered by seq so a client resumes exactly where it left off
// regardless of which capture each mutation touched. limit is passed as
// requested-page-size+1 by the caller so it can detect has_more without a
// second COUNT query.
func (q *Queries) ListMutationsSinceRevision(ctx context.Context, arg ListMutationsSinceRevisionParams) ([]Mutation, error) {
	rows, err := q.db.Query(ctx, listMutationsSinceRevision, arg.WorkspaceID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mutation
	for rows.Next() {
		var i Mutation
		if err := rows.Scan(
			&i.ID,
			&i.CaptureID,
			&i.Op,
			&i.Payload,
			&i.ClientT,
			&i.CreatedAt,
			&i.WorkspaceID,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByWorkspace = `-- name: ListProjectsByWorkspace :many
SELECT id, workspace_id, name, created_at FROM projects WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListProjectsByWorkspace(ctx context.Context, workspaceID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.created_at, w.policy_overrides FROM workspaces w
JOIN memberships m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at
`

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.PolicyOverrides,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCaptureForWorkspace = `-- name: LockCaptureForWorkspace :one
SELECT id, workspace_id, project_id, source, state, fidelity, created_at, epoch, env, metadata, doc, withheld_event_count, revision, manifest_complete, applied_ruleset_version FROM captures WHERE id = $1 AND workspace_id = $2 FOR UPDATE
`

type LockCaptureForWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

// Workspace and existence are checked in one predicate so a mutation
// naming a capture outside the caller's workspace fails the same way as a
// mutation naming a capture that doesn't exist at all — the caller cannot
// tell the two cases apart, which is the point (no existence leak across
// workspaces). FOR UPDATE serializes concurrent revision increments on the
// same capture.
func (q *Queries) LockCaptureForWorkspace(ctx context.Context, arg LockCaptureForWorkspaceParams) (Capture, error) {
	row := q.db.QueryRow(ctx, lockCaptureForWorkspace, arg.ID, arg.WorkspaceID)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Source,
		&i.State,
		&i.Fidelity,
		&i.CreatedAt,
		&i.Epoch,
		&i.Env,
		&i.Metadata,
		&i.Doc,
		&i.WithheldEventCount,
		&i.Revision,
		&i.ManifestComplete,
		&i.AppliedRulesetVersion,
	)
	return i, err
}

const markAssetVerified = `-- name: MarkAssetVerified :one
UPDATE assets SET sha256 = $2, size_bytes = $3, verified_at = now() WHERE id = $1 RETURNING id, capture_id, kind, mime_type, size_bytes, chunk_count, sha256, object_key, verified_at, created_at
`

type MarkAssetVerifiedParams struct {
	ID        string      `json:"id"`
	Sha256    pgtype.Text `json:"sha256"`
	SizeBytes int64       `json:"size_bytes"`
}

func (q *Queries) MarkAssetVerified(ctx context.Context, arg MarkAssetVerifiedParams) (Asset, error) {
	row := q.db.QueryRow(ctx, markAssetVerified, arg.ID, arg.Sha256, arg.SizeBytes)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Kind,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.Sha256,
		&i.ObjectKey,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeShareLink = `-- name: RevokeShareLink :one
UPDATE share_links SET revoked_at = now() WHERE id = $1 RETURNING id, capture_id, token, created_by, revoked_at, expires_at, created_at
`

func (q *Queries) RevokeShareLink(ctx context.Context, id string) (ShareLink, error) {
	row := q.db.QueryRow(ctx, revokeShareLink, id)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Token,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const setCaptureManifestComplete = `-- name: SetCaptureManifestComplete :one
UPDATE captures SET manifest_complete = $2 WHERE id = $1 RETURNING id, workspace_id, project_id, source, state, fidelity, created_at, epoch, env, metadata, doc, withheld_event_count, revision, manifest_complete, applied_ruleset_version
`

type SetCaptureManifestCompleteParams struct {
	ID               string `json:"id"`
	ManifestComplete bool   `json:"manifest_complete"`
}

func (q *Queries) SetCaptureManifestComplete(ctx context.Context, arg SetCaptureManifestCompleteParams) (Capture, error) {
	row := q.db.QueryRow(ctx, setCaptureManifestComplete, arg.ID, arg.ManifestComplete)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Source,
		&i.State,
		&i.Fidelity,
		&i.CreatedAt,
		&i.Epoch,
		&i.Env,
		&i.Metadata,
		&i.Doc,
		&i.WithheldEventCount,
		&i.Revision,
		&i.ManifestComplete,
		&i.AppliedRulesetVersion,
	)
	return i, err
}

const updateCaptureRevisionAndDoc = `-- name: UpdateCaptureRevisionAndDoc :one
UPDATE captures SET revision = $2, doc = $3 WHERE id = $1 RETURNING id, workspace_id, project_id, source, state, fidelity, created_at, epoch, env, metadata, doc, withheld_event_count, revision, manifest_complete, applied_ruleset_version
`

type UpdateCaptureRevisionAndDocParams struct {
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
	Doc      []byte `json:"doc"`
}

func (q *Queries) UpdateCaptureRevisionAndDoc(ctx context.Context, arg UpdateCaptureRevisionAndDocParams) (Capture, error) {
	row := q.db.QueryRow(ctx, updateCaptureRevisionAndDoc, arg.ID, arg.Revision, arg.Doc)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Source,
		&i.State,
		&i.Fidelity,
		&i.CreatedAt,
		&i.Epoch,
		&i.Env,
		&i.Metadata,
		&i.Doc,
		&i.WithheldEventCount,
		&i.Revision,
		&i.ManifestComplete,
		&i.AppliedRulesetVersion,
	)
	return i, err
}

const updateProjectForWorkspace = `-- name: UpdateProjectForWorkspace :one
UPDATE projects SET name = $3 WHERE id = $1 AND workspace_id = $2 RETURNING id, workspace_id, name, created_at
`

type UpdateProjectForWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) UpdateProjectForWorkspace(ctx context.Context, arg UpdateProjectForWorkspaceParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectForWorkspace, arg.ID, arg.WorkspaceID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET name = $2 WHERE id = $1 RETURNING id, name, created_at, policy_overrides
`

type UpdateWorkspaceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.PolicyOverrides,
	)
	return i, err
}

const updateWorkspacePolicyOverrides = `-- name: UpdateWorkspacePolicyOverrides :one
UPDATE workspaces SET policy_overrides = $2 WHERE id = $1 RETURNING id, name, created_at, policy_overrides
`

type UpdateWorkspacePolicyOverridesParams struct {
	ID              string `json:"id"`
	PolicyOverrides []byte `json:"policy_overrides"`
}

func (q *Queries) UpdateWorkspacePolicyOverrides(ctx context.Context, arg UpdateWorkspacePolicyOverridesParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspacePolicyOverrides, arg.ID, arg.PolicyOverrides)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.PolicyOverrides,
	)
	return i, err
}

const upsertAssetForUpload = `-- name: UpsertAssetForUpload :one
INSERT INTO assets (id, capture_id, kind, mime_type, size_bytes, chunk_count, sha256, object_key)
VALUES ($1, $2, $3, $4, $5, 0, NULL, $6)
ON CONFLICT (id) DO UPDATE SET object_key = EXCLUDED.object_key
RETURNING id, capture_id, kind, mime_type, size_bytes, chunk_count, sha256, object_key, verified_at, created_at
`

type UpsertAssetForUploadParams struct {
	ID        string `json:"id"`
	CaptureID string `json:"capture_id"`
	Kind      string `json:"kind"`
	MimeType  string `json:"mime_type"`
	SizeBytes int64  `json:"size_bytes"`
	ObjectKey string `json:"object_key"`
}

// Creates the manifest entry (ADR-012: "the manifest entry for each asset
// carries the expected size and content hash before the PUT is issued") on
// first request, or repoints object_key at a freshly minted key on
// re-request. sha256/size_bytes/verified_at are deliberately left untouched
// here — they only ever change via MarkAssetVerified, so a re-request can
// never itself flip a verified asset back to unverified.
func (q *Queries) UpsertAssetForUpload(ctx context.Context, arg UpsertAssetForUploadParams) (Asset, error) {
	row := q.db.QueryRow(ctx, upsertAssetForUpload,
		arg.ID,
		arg.CaptureID,
		arg.Kind,
		arg.MimeType,
		arg.SizeBytes,
		arg.ObjectKey,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Kind,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChunkCount,
		&i.Sha256,
		&i.ObjectKey,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCaptureFieldVersion = `-- name: UpsertCaptureFieldVersion :one
INSERT INTO capture_field_versions (capture_id, field, server_t, revision, mutation_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (capture_id, field) DO UPDATE
    SET server_t = EXCLUDED.server_t, revision = EXCLUDED.revision, mutation_id = EXCLUDED.mutation_id
RETURNING capture_id, field, server_t, revision, mutation_id
`

type UpsertCaptureFieldVersionParams struct {
	CaptureID  string             `json:"capture_id"`
	Field      string             `json:"field"`
	ServerT    pgtype.Timestamptz `json:"server_t"`
	Revision   int64              `json:"revision"`
	MutationID string             `json:"mutation_id"`
}

func (q *Queries) UpsertCaptureFieldVersion(ctx context.Context, arg UpsertCaptureFieldVersionParams) (CaptureFieldVersion, error) {
	row := q.db.QueryRow(ctx, upsertCaptureFieldVersion,
		arg.CaptureID,
		arg.Field,
		arg.ServerT,
		arg.Revision,
		arg.MutationID,
	)
	var i CaptureFieldVersion
	err := row.Scan(
		&i.CaptureID,
		&i.Field,
		&i.ServerT,
		&i.Revision,
		&i.MutationID,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, email, name) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name
RETURNING id, email, name, created_at
`

type UpsertUserParams struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

// Identity is minted by the IdP (the OIDC subject), not by us, so first
// login upserts a local user row keyed on that subject rather than
// inserting and failing on conflict.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
